# -*- coding: utf-8 -*-
"""matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SxuMa3xLdae6dMt2HJWWxnBsFcNAK1A1
"""

import matplotlib.pyplot as plt   # import matplotlib

# sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# create a simple line chart
plt.plot(x, y)

# add labels and title
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Simple Line Chart")

# show the graph
plt.show()