# -*- coding: utf-8 -*-
"""numpySimpleProgram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kqEfsJLuH9SCP-IOcYigJh-CBDBA9F8
"""

import numpy as np   # import numpy library

# create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# perform operations
print("Original array:", arr)
print("Array multiplied by 2:", arr * 2)
print("Sum of elements:", np.sum(arr))
print("Mean of elements:", np.mean(arr))