# -*- coding: utf-8 -*-
"""Pandas_Library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njwb0ZyMeu0PxQyGx54pQTdQnOX2lvPb
"""

import pandas as pd   # import pandas library

# Create a simple DataFrame (like a table)

data = {
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 22, 19],
    "City": ["Karachi", "Lahore", "Islamabad"]
}

df = pd.DataFrame(data)

# Display the table
print(df)