# -*- coding: utf-8 -*-
"""sklearn_Library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPL4nvjVWmhtIY4T6uuR-EvQ-pggtA-_
"""

from sklearn.linear_model import LinearRegression
import numpy as np

# training data (x: study hours, y: exam score)
x = np.array([[1], [2], [3], [4], [5]])   # features
y = np.array([20, 40, 60, 80, 100])       # labels

# create the model
model = LinearRegression()

# train (fit) the model
model.fit(x, y)

# predict score for 6 study hours
prediction = model.predict([[6]])
print("Predicted score for 6 study hours:", prediction[0])