# -*- coding: utf-8 -*-
"""Statsmodels_Library.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOqkkTJd-AxxiFJWKesSv5_egVvKpLmk
"""

import statsmodels.api as sm
import numpy as np

# training data (x: study hours, y: exam score)
x = np.array([1, 2, 3, 4, 5])   # independent variable
y = np.array([20, 40, 60, 80, 100])  # dependent variable

# add a constant for the intercept
x = sm.add_constant(x)

# create and fit the model
model = sm.OLS(y, x).fit()

# print summary
print(model.summary())