# -*- coding: utf-8 -*-
"""ArmStrongNumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kspxRPxW4bnosgPUQgs313iWKnkBgQsD
"""

num = int(input("enter a number here: "))

sum = 0
temp = num

while temp > 0:
    digit = temp % 10
    cube = digit ** 3
    sum = sum + cube
    temp //= 10

if sum == num:
    print('it is an armstrong number')
else:
    print("it is not an armstrong number")