# -*- coding: utf-8 -*-
"""checkTheNumber_Is_EvenOrOdd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqWNa9SazPI5Oquc50pvLylnjoub_V5F
"""

num=int(input("Enter Any number "))

if num%2==0:
  print("The Number is Even ", num)
else:
  print("The number is Odd", num)