# -*- coding: utf-8 -*-
"""check_prime_Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LD-ry1AiFjYSpkBqomh0Zirhf4QPuIPf
"""

num=int(input("Enter_Any_Number"))
if num==1:
  print("it is Not a prime number ")
if num>1:
  for i in range (2,num):
      if num%i==0:
         print("it is not a prime number")
         break
  else:
      print("prime_Number")