# -*- coding: utf-8 -*-
"""Check_IfNumberIsPositiveNegOrZero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXvHxLg_z4hasdQJ7HAlrHRH3kmdYMnd
"""

num = int(input("Enter_Any_Number_For_Check_"))

if num>0:
  print("The Number is Positive", num)
elif num<0:
  print("The Number is Neg", num )
else:
    print("The number is Zero ", num)