# -*- coding: utf-8 -*-
"""Day1_AddTwoNumbers_Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XcPtzUj-X1vBkmbkvzGmJVnjqZ_S1QlT
"""

#Soution1 (With Pre_defined Variables)

num1=20
num2=10
print("The_Sum_Of_Two_Numbers_is ",num1+num2)

#Solution2 (With_User_Input)
num1=int(input("ENter Your First Number "))
num2=int(input("Enter Your Second Number "))


print("THe Sum Of Two Numbers Are ", num1+num2)

