# -*- coding: utf-8 -*-
"""Day1_Calculating_the_SquareRoot_OfAnyNumber

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j70iwMEXjHzUSf8Eo-cQX0nJpt3DQgHr
"""

# Method 1 Using The Exponentiation
num1=64
square_Root= num1**(1/2) #Or We can also write(0.5)
print("Square_Root_of_num1_is",square_Root)

#SEcond_Method Using the mathModulde
#Using the sqrt() Function
#For That we have to Import first math Library
import math
num1=81
result = math.sqrt(num1)
print("The Square_Root Of Given Number is ",result)

