# -*- coding: utf-8 -*-
"""Day2_KmToMiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vSBHBuxrZ6-zX-mPfxM_BcYG3ceOcrVN
"""

km=float(input("ENter The Km "))
miles=(0.621371)*km

print(km , "km in miles will be ", miles ," Miles ")