# -*- coding: utf-8 -*-
"""Day2_SwapTwoVariable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wz7Q9k-6Ff8Baba2RjOx0xuLEQ1ju6cL
"""

# Swap Two Variables using the third variable

a=30
b=20
print("before_Swapping_Value_Of a is", a ,"After Swapping Value OF b is", b)

t=a  # so here t=30
a=b  # now here a=20
b=t   # now here b=30

print("After Swapping the Value The value of a is ", a ,"The Value Of B is ", b)