# -*- coding: utf-8 -*-
"""Day2_Finding_The_LeapYear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1er96W0O4taNMtA8L3mKX4YXG9sCovxTa
"""

year = int(input("Enter a year"))

if year%400==0 and year%100==0:
  print("Leap Year is ", year )
elif year%4==0 and year%100 !=0:
  print("This Is  The Leap Year ", year)
else:
    print("Not a leap Year", year)