# -*- coding: utf-8 -*-
"""Day2_CalculatingTheAreaOfTheTriange.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11lTDktiySDpbCZjjpqfcucrkTqThgwFO
"""

#Finding The Area Of The Triange
#Formula Area=1/2 width * Height

height = float(input("Enter_Your_Height_Number"))
width = float(input("Enter_Your_Width_Number"))
area_Of_Triange=1/2*(width*height)
print(area_Of_Triange)