# -*- coding: utf-8 -*-
"""Factorial_Of_Number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RTPZCBz8sANW1Jg9HfjSmOwQtPGTpdu9
"""

num=1
factorial=4

while(num>0):
  num=num*factorial
  factorial=factorial-1
  if factorial==0:
    break
  print(num)