# -*- coding: utf-8 -*-
"""fibonacci_Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CqgR24ZCDLf0qYml3EFb4Aia_Owv4FT
"""

a=0
b=1
num=int(input("Enter Any number for finding its f_Series "))
if num==1:
  print(a)
else:
  print(a)
  print(b)
  for i in range (1,num+1):
    print(num)
    c=a+b
    a=b
    b=c
    print(c)