# -*- coding: utf-8 -*-
"""FindTheLargestNumberAmongTheThreeNumbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHktHJf7O_GEf-VjYEJ-yHlhaW9aWReH
"""

num1 =int(input("Enter Your First Number"))
num2 =int(input("Enter Your second Number"))
num3 =int(input("Enter Your third Number"))

if num1>num2 and num1>num3:
  print("Larger number is ", num1)
elif num2>num1 and num2>num3:
  print("larger number is ", num2)
else:
  print("Larger number is ", num3)