# -*- coding: utf-8 -*-
"""Program to Display Powers of 2 Using Anonymous Function..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13P1Xxh_O1U1MUFDwHVZ8YjQS4YMUWc60
"""

# Program to display powers of 2 using anonymous function

# take input from user
n = int(input("Enter the number of terms: "))

# use lambda to calculate power of 2
powers_of_two = list(map(lambda x: 2 ** x, range(n)))

# display result
print("The powers of 2 are:")
for i in range(n):
    print("2 raised to power", i, "is", powers_of_two[i])