# -*- coding: utf-8 -*-
"""SumOfNaturalNumbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OY0kf1g2FCD6ciYYuLFjdSdwcKrT7uKG
"""

# Program to find the sum of natural numbers up to n

n = int(input("Enter a positive number: "))

sum = 0

for i in range(1, n + 1):
    sum += i

print("The sum of natural numbers up to", n, "is:", sum)