# -*- coding: utf-8 -*-
"""tableUsingLoop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2Q_QQjNM3jrdDDoVRK4HtjhyUscKcZl
"""

table=int(input("Enter_Any_Number"))
for i in range (1,11):
  print(table, " * ", i ," = ",i*table)