# -*- coding: utf-8 -*-
"""ToGenerateARandomNumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2QHauoU197-7Vcx4GW2GNK-pkUaUOps
"""

import random
num = random.randint(1,10)

print(num)